FROM arm64v8/golang:1.24-bookworm AS builder

RUN apt-get update && apt-get install -y gcc-aarch64-linux-gnu
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 CC=aarch64-linux-gnu-gcc GOOS=linux GOARCH=arm64 go build -o app .

FROM shinsenter/scratch:latest

WORKDIR /root/
    
COPY --from=builder /go/app .

CMD ["./app", "--config.file=config.yaml"]