FROM golang:1.24-bookworm AS builder

RUN apt-get update
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o app .

FROM scratch
WORKDIR /root/

COPY --from=builder /go/app .

CMD ["./app", "--config.file=config.yaml"]