name: "Deploying image"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    # - name: Set up Docker Buildx
    #   uses: docker/setup-buildx-action@v3

    - name: Build the Docker image
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
      run: docker build --file Dockerfile --platform linux/arm64/v8 -t $DOCKER_USER/status-blog --no-cache .

    # - name: Docker Push
    #   env:
    #     DOCKER_USER: ${{secrets.DOCKER_USER}}
    #   run: docker push $DOCKER_USER/status-blog