name: "Deploying image"

on:
  workflow_dispatch:
    inputs:
      dockerhub_operation:
        description: "Building arm64 and amd64 Image and Deploy status-page on Dockerhub"
        required: true
        default: "apply"
        type: choice
        options:
          - apply

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    # - name: Build the Docker image
    #   env:
    #     DOCKER_USER: ${{secrets.DOCKER_USER}}
    #     REPO_NAME: ${{ github.event.repository.name }}
    #   run: |
    #     docker build --file Dockerfile_arm64 --platform linux/arm64/v8 -t $DOCKER_USER/$REPO_NAME:arm64 .
    #     docker push $DOCKER_USER/$REPO_NAME:arm64
      
    #     docker build --file Dockerfile_amd64 -t $DOCKER_USER/$REPO_NAME:amd64 .
    #     docker push $DOCKER_USER/$REPO_NAME:amd64
    #   if: "${{ github.event.inputs.dockerhub_operation == 'apply' }}"

    - name: Build the Docker image arm64
      uses: docker/build-push-action@v6
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
      with:
        file: ./Dockerfile_arm64
        platforms: linux/arm64/v8
        context: "{{defaultContext}}"
        push: true
        tags: >
          docker.io/$DOCKER_USER/${{ github.event.repository.name }}:arm64

    - name: Build the Docker image arm64
      uses: docker/build-push-action@v6
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
      with:
        file: ./Dockerfile_amd64
        platforms: linux/amd64
        context: "{{defaultContext}}"
        push: true
        tags: >
          docker.io/$DOCKER_USER/${{ github.event.repository.name }}:amd64