name: "Deploying image"

on:
  workflow_dispatch:
    inputs:
      dockerhub_operation:
        description: "Building arm64 and amd64 Image and Deploy status-page on Dockerhub"
        required: true
        default: "apply"
        type: choice
        options:
          - apply

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Build the Docker image arm64
      uses: docker/build-push-action@v6
      with:
        file: ./Dockerfile_arm64
        platforms: linux/arm64/v8
        context: .
        push: true
        tags: ${{secrets.DOCKER_USER}}/${{ github.event.repository.name }}:arm64

    - name: Build the Docker image amd64
      uses: docker/build-push-action@v6
      with:
        file: ./Dockerfile_amd64
        platforms: linux/amd64
        context: .
        push: true
        tags: ${{secrets.DOCKER_USER}}/${{ github.event.repository.name }}:amd64